/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mathx_Stats */

#ifndef _Included_Mathx_Stats
#define _Included_Mathx_Stats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mathx_Stats
 * Method:    mean
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_00024Stats_mean___3D
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     Mathx_Stats
 * Method:    mean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_00024Stats_mean___3I
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     Mathx_Stats
 * Method:    mean
 * Signature: ([J)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_00024Stats_mean___3J
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     Mathx_Stats
 * Method:    mean
 * Signature: ([F)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_00024Stats_mean___3F
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     Mathx_Stats
 * Method:    stdDev
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_00024Stats_stdDev___3D
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     Mathx_Stats
 * Method:    stdDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_00024Stats_stdDev___3I
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     Mathx_Stats
 * Method:    stdDev
 * Signature: ([J)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_00024Stats_stdDev___3J
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     Mathx_Stats
 * Method:    stdDev
 * Signature: ([F)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_00024Stats_stdDev___3F
  (JNIEnv *, jclass, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
