/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mathx */

#ifndef _Included_Mathx
#define _Included_Mathx
#ifdef __cplusplus
extern "C" {
#endif
#undef Mathx_Euler
#define Mathx_Euler 2.7182818284590455
#undef Mathx_PI
#define Mathx_PI 3.141592653589793
#undef Mathx_LN10
#define Mathx_LN10 2.302585092994046
/*
 * Class:     Mathx
 * Method:    stdDev
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_stdDev(JNIEnv *, jclass, jdoubleArray);
JNIEXPORT jdouble JNICALL Java_Mathx_cos(JNIEnv *, jclass, jdouble);
JNIEXPORT jdouble JNICALL Java_Mathx_sin(JNIEnv *, jclass, jdouble);
JNIEXPORT jdouble JNICALL Java_Mathx_sqrt(JNIEnv *, jclass, jdouble);
JNIEXPORT jdouble JNICALL Java_Mathx_power(JNIEnv *, jclass, jdouble, jint);
JNIEXPORT jdouble JNICALL Java_Mathx_factorial(JNIEnv *, jclass, jint);
JNIEXPORT jdouble JNICALL Java_Mathx_exp(JNIEnv *, jclass, jdouble);
JNIEXPORT jdouble JNICALL Java_Mathx_ln(JNIEnv *, jclass, jdouble);
JNIEXPORT jdouble JNICALL Java_Mathx_pi(JNIEnv *, jclass, jint);
JNIEXPORT jdouble JNICALL Java_Mathx_euler(JNIEnv *env, jclass clazz, jint n);
#ifdef __cplusplus
}
#endif
#endif
