/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mathx_Geo */

#ifndef _Included_Mathx_Geo
#define _Included_Mathx_Geo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mathx_Geo
 * Method:    sin
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_00024Geo_sin
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     Mathx_Geo
 * Method:    cos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Mathx_00024Geo_cos
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
